// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as Rxjs from "rxjs";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Operators from "rxjs/operators";

var oneObs = Rxjs.Observable.create((function (obs) {
        obs.next(10);
        obs.complete();
        return /* () */0;
      }));

var twoObs = Rxjs.Observable.create((function (obs) {
        obs.next(100);
        obs.next(200);
        obs.complete();
        return /* () */0;
      }));

Jest.describe("Operators", (function (param) {
        Jest.testAsync("map", undefined, (function (finish) {
                var testObs = Curry._1(Operators.map((function (x) {
                            return x + 10 | 0;
                          })), oneObs);
                testObs.subscribe((function (value) {
                        return Curry._1(finish, Jest.Expect[/* toBe */2](20, Jest.Expect[/* expect */0](value)));
                      }));
                return /* () */0;
              }));
        return Jest.testAsync("mapTo", undefined, (function (finish) {
                      var testObs = Curry._1(Operators.mapTo(20), oneObs);
                      testObs.subscribe((function (value) {
                              return Curry._1(finish, Jest.Expect[/* toBe */2](20, Jest.Expect[/* expect */0](value)));
                            }));
                      return /* () */0;
                    }));
      }));

export {
  oneObs ,
  twoObs ,
  
}
/* oneObs Not a pure module */
