// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Rxjs = require("rxjs");

var bnc1 = Rxjs.bindNodeCallback((function (prim, prim$1) {
        Fs.readFile(prim, prim$1);
        return /* () */0;
      }));

var bnc2 = Rxjs.bindNodeCallback((function (prim, prim$1, prim$2) {
        Fs.readFile(prim, prim$1, prim$2);
        return /* () */0;
      }));

var z1 = bnc1("/home/harshal/ub/bs-marble/README.md");

var z2 = bnc2("/home/harshal/ub/bs-marble/README.md", "utf-8");

z1.subscribe((function (y) {
        console.log(y);
        return /* () */0;
      }));

z2.subscribe((function (y) {
        console.log(y);
        return /* () */0;
      }));

exports.bnc1 = bnc1;
exports.bnc2 = bnc2;
exports.z1 = z1;
exports.z2 = z2;
/* bnc1 Not a pure module */
