// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Rxjs from "rxjs";
import * as Operators from "rxjs/operators";

var stream1 = Rxjs.Observable.create((function (obs) {
        obs.next(30);
        return /* () */0;
      }));

var subscription1 = stream1.subscribe((function (myVal) {
        return /* () */0;
      }));

var subscription2 = stream1.subscribe(observer1);

subscription1.unsubscribe();

Operators.map((function (x) {
        return x + 5 | 0;
      }), Operators.map((function (item, index) {
            return (item + index | 0) + 4 | 0;
          }), Operators.map((function (item) {
                return item + 3 | 0;
              }), stream1)));

export {
  stream1 ,
  subscription1 ,
  subscription2 ,
  
}
/* stream1 Not a pure module */
