// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Rxjs from "rxjs";

var y = Rxjs.Observable.create((function (obs) {
        obs.next(20);
        return /* () */0;
      }));

export {
  y ,
  
}
/* y Not a pure module */
