// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Rxjs from "rxjs";
import * as Curry from "bs-platform/lib/es6/curry.js";

function defer(factory, stream) {
  return Curry._1(Rxjs.defer((function () {
                    return Curry._1(factory, /* () */0);
                  })), stream);
}

function deferPromise(factory, stream) {
  return Curry._1(Rxjs.defer((function () {
                    return Curry._1(factory, /* () */0);
                  })), stream);
}

function deferArray(factory, stream) {
  return Curry._1(Rxjs.defer(factory), stream);
}

export {
  defer ,
  deferPromise ,
  deferArray ,
  
}
/* rxjs Not a pure module */
