// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Operators from "rxjs/operators";

function repeat($staropt$star, stream) {
  var count = $staropt$star !== undefined ? $staropt$star : -1;
  return Curry._1(Operators.repeat(count), stream);
}

function find(predicate, source) {
  return Curry._1(Operators.map((function (prim) {
                    if (prim === undefined) {
                      return undefined;
                    } else {
                      return Caml_option.some(prim);
                    }
                  })), Curry._1(Operators.find(Curry.__3(predicate)), source));
}

export {
  repeat ,
  find ,
  
}
/* rxjs/operators Not a pure module */
